# Settings for the webserver
server:
  # Key to sign cookies
  jwt-key: config/jwt.pem
  # Port to run the server on
  port: 8001
  # HTTPS config for running an HTTPS server
  https-config:
    # Port to run HTTP server which redirects to HTTPS (optional)
    http-port: 8000
    # HTTPS certificate
    cert: config/cert.pem
    # HTTPS private key
    key: config/key.pem
  
  # HTTPS config for using a resolver
  # Resolver to use (xForwardedProto or forwarded)
  # See https://hackage.haskell.org/package/wai-enforce-https/docs/Network-Wai-Middleware-EnforceHTTPS.html
  # resolver: forwarded

# Database settings
db:
  host: localhost
  port: 5432
  db: app
  user: user
  password: password
  pools: 8

# SMTP configuration (optional)
smtp:
  hostname: smtp.example.com
  username: app@example.com
  password: example
  # The default address to send emails from (can be overridden on a per email basis)
  default-from:
    # The name field is optional - if its omitted emails appear as just from the address 
    name: "App"
    address: "no-reply@example.com"
